import * as fs from 'node:fs/promises';
import * as path from 'node:path';

export class Generator {
  private filePath: string;

  constructor() {
    // タイムスタンプ付きのファイル名を生成
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    this.filePath = path.join(process.cwd(), `generated_test_${timestamp}.spec.ts`);
  }

  async init(goal: string) {
    const header = `import { test, expect } from '@playwright/test';

/**
 * Goal: ${goal}
 * Generated by Flash-Loop v2
 */
test('FlashLoop Auto-Generated Test', async ({ page }) => {
  // Setup default timeout
  test.setTimeout(60000);
`;
    await fs.writeFile(this.filePath, header, 'utf-8');
  }

  async appendCode(code: string) {
    // インデントを追加して書き込み
    const indentedCode = code
      .split('\n')
      .map((line) => `  ${line}`)
      .join('\n');
    await fs.appendFile(this.filePath, `${indentedCode}\n`, 'utf-8');
  }

  async finish() {
    await fs.appendFile(this.filePath, '});\n', 'utf-8');
  }

  getFilePath() {
    return this.filePath;
  }
}
