import * as fs from 'node:fs/promises';
import * as path from 'node:path';

export class Generator {
  private filePath: string;

  constructor() {
    // プロジェクトルートに 'generated.spec.ts' という名前で保存します
    // 必要に応じてタイムスタンプ付きのファイル名などに変更してください
    this.filePath = path.join(process.cwd(), 'generated.spec.ts');
  }

  /**
   * テストファイルを初期化し、ヘッダー（import文など）を書き込みます
   */
  async init() {
    const header = `import { test, expect } from '@playwright/test';

test('FlashLoop Generated Test', async ({ page }) => {
  // Auto-generated by FlashLoop
  // Setup default timeout for AI interaction
  test.setTimeout(120000);
`;
    await fs.writeFile(this.filePath, header, 'utf-8');
    console.log(`📄 Created test file: ${this.filePath}`);
  }

  /**
   * 生成されたコードをファイルに追記します
   */
  async appendCode(code: string) {
    // 読みやすさのためにインデントを追加して書き込みます
    const indentedCode = code
      .split('\n')
      .map((line) => `  ${line}`)
      .join('\n');
    await fs.appendFile(this.filePath, `${indentedCode}\n`, 'utf-8');
  }

  /**
   * テストブロックの閉じ括弧を書き込んでファイルを完成させます
   */
  async finish() {
    await fs.appendFile(this.filePath, '});\n', 'utf-8');
  }

  getFilePath() {
    return this.filePath;
  }
}
